### ISSUE TITLE
TypeError: No registered converter was able to produce a C++ rvalue of type bytes from this Python object of type sha1_hash

### ISSUE THREAD

**Issue by ghost** [inaz2/btsniff#1]
how can i fix this  error ?

#############################################################################

[root@ torrent-test]# python btsniff.py ubuntu-12.04.5-alternate-amd64.iso.torrent
[listen_succeeded_alert] successfully listening on [TCP] 0.0.0.0:6881
[listen_succeeded_alert] successfully listening on [TCP/SSL] 0.0.0.0:4433
[listen_succeeded_alert] successfully listening on [TCP] [::]:6881
[listen_succeeded_alert] successfully listening on [TCP/SSL] [::]:4433
[listen_succeeded_alert] successfully listening on [UDP] 0.0.0.0:6881
[alert] DHT bootstrap complete
[torrent_added_alert] ubuntu-12.04.5-alternate-amd64.iso added
[add_torrent_alert] added torrent: ubuntu-12.04.5-alternate-amd64.iso
[torrent_resumed_alert] ubuntu-12.04.5-alternate-amd64.iso resumed
[state_changed_alert] ubuntu-12.04.5-alternate-amd64.iso: state changed to: checking (q)
[state_changed_alert] ubuntu-12.04.5-alternate-amd64.iso: state changed to: checking
[alert] DHT error [hostname lookup] (1) Host not found (authoritative)
[state_changed_alert] ubuntu-12.04.5-alternate-amd64.iso: state changed to: downloading
[torrent_checked_alert] ubuntu-12.04.5-alternate-amd64.iso checked
[torrent_resumed_alert] ubuntu-12.04.5-alternate-amd64.iso resumed
[torrent_paused_alert] ubuntu-12.04.5-alternate-amd64.iso paused
[torrent_paused_alert] ubuntu-12.04.5-alternate-amd64.iso paused
[external_ip_alert] external IP received: 45.22.86.66
[dht_get_peers_alert] incoming dht get_peers: 5f49470b5d1ab1fee730c1a1a128ea7f8f1418d2
Traceback (most recent call last):
  File "btsniff.py", line 96, in <module>
    btsniff.start(torrent_file)
  File "btsniff.py", line 34, in start
    self.handle_alert(alert)
  File "btsniff.py", line 63, in handle_alert
    h = self.ses.add_torrent({'info_hash': alert.info_hash, 'save_path': './'})
TypeError: No registered converter was able to produce a C++ rvalue of type bytes from this Python object of type sha1_hash
#############################################################################

Thanks

**Comment by inaz2** [comment]
Read the error message. Thank you for the bug report.
